image: node

before_script:
  - yarn

cache:
  paths:
    - node_modules/

pages:
  script:
  - yarn build
  - rm -rf public
  - mv dist public
  artifacts:
    paths:
      - public
  only:
    - master
